---

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-github-metadata

defaults:
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      classes: wide
      layout: single

minimal_mistakes_skin: air
title: React Routeways
subtitle: Use ts-routeways and react-router-dom together
name: Jose Luis Leon
repository: JoseLion/react-routeways
atom_feed:
  hide: true
twitter:
  username: joseliont
author:
  name: Jose Luis Leon
  avatar: https://github.com/JoseLion.png
  email: joseluis5000l@gmail.com
  links:
    - label: Repository
      icon: fab fa-fw fa-github
      url: https://github.com/JoseLion/react-routeways
    - label: GitHub
      icon: fab fa-fw fa-github-alt
      url: https://github.com/JoseLion
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/joseliont
footer:
  links:
    - label: Repository
      icon: fab fa-fw fa-github
      url: https://github.com/JoseLion/react-routeways
    - label: GitHub
      icon: fab fa-fw fa-github-alt
      url: https://github.com/JoseLion
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/joseliont

...
